# Generated by Django 4.1.3 on 2022-11-05 14:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('date_of_birth', models.DateField(verbose_name='Date of birth')),
                ('iin_number', models.IntegerField(verbose_name='IIN')),
                ('id_number', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('fname', models.CharField(max_length=50, verbose_name='First Name')),
                ('mname', models.CharField(max_length=50, verbose_name='Middle Name')),
                ('lname', models.CharField(max_length=50, verbose_name='Last Name')),
                ('blood_group', models.CharField(max_length=5, verbose_name='Blood group')),
                ('emergency_contact_number', models.CharField(max_length=12, verbose_name='Emergency contact number')),
                ('contact_number', models.CharField(max_length=12, verbose_name='Contact Number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email address')),
                ('address', models.CharField(max_length=1024, verbose_name='Physical address')),
                ('martial_status', models.CharField(max_length=20, verbose_name='Martial status')),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
