# Generated by Django 4.1.3 on 2022-11-05 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='iin_number',
            field=models.CharField(max_length=12, verbose_name='IIN'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='martial_status',
            field=models.CharField(choices=[('Married', 'Married'), ('Not Married', 'Nor Married')], max_length=20, verbose_name='Martial status'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Middle Name'),
        ),
    ]
