# Generated by Django 4.1.3 on 2022-11-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_patient_iin_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='martial_status',
            field=models.CharField(choices=[('Married', 'Married'), ('Not Married', 'Not Married')], max_length=20, verbose_name='Martial status'),
        ),
    ]
