# Generated by Django 4.1.3 on 2022-11-05 18:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_patient_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('date_of_birth', models.DateField(verbose_name='Date of birth')),
                ('iin_number', models.CharField(max_length=12, verbose_name='IIN')),
                ('id_number', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('fname', models.CharField(max_length=50, verbose_name='First Name')),
                ('mname', models.CharField(blank=True, max_length=50, null=True, verbose_name='Middle Name')),
                ('lname', models.CharField(max_length=50, verbose_name='Last Name')),
                ('contact_number', models.CharField(max_length=12, verbose_name='Contact Number')),
                ('department_id', models.IntegerField(verbose_name='Department ID')),
                ('specialization_details_id', models.IntegerField(verbose_name='Specialization Details ID')),
                ('experience', models.CharField(max_length=4, verbose_name='Experience In Years')),
                ('category', models.CharField(max_length=100, verbose_name='Category')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('schedule_details', models.CharField(max_length=100, verbose_name='Schedule Details')),
                ('education', models.CharField(choices=[('No Education', 'No Education'), ('High School Diploma', 'High School Diploma'), ('Cerificate or associate degree', 'Cerificate or associate degree'), ("Bachelor's Degree", "Bachelor's Degree"), ("Master's Degree", "Master's Degree"), ('Doctorate', 'Doctorate')], max_length=50, verbose_name='Degree of Education')),
                ('rating', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=3, verbose_name='Rating')),
                ('address', models.CharField(max_length=1024, verbose_name='Address')),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
            },
        ),
    ]
