# Generated by Django 4.1.3 on 2022-11-06 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='education',
            field=models.CharField(choices=[('No Education', 'No Education'), ('High School Diploma', 'High School Diploma'), ('Certificate or associate degree', 'Certificate or associate degree'), ("Bachelor's Degree", "Bachelor's Degree"), ("Master's Degree", "Master's Degree"), ('Doctorate', 'Doctorate')], max_length=50, verbose_name='Degree of Education'),
        ),
    ]
